// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /cms/kyriacou/PFPho/CUTBasedID/CMSSW_7_0_0/src/GACUTS/CSA14.h;
#pragma link C++ defined_in "/cms/kyriacou/PFPho/CUTBasedID/CMSSW_7_0_0/src/GACUTS/CSA14.C";

#endif
