#include "sstream"
#include <string>

void Fitter(double e_min,double e_max,int bin,double &isoP,double &isoC,double &isoN){
  //------------Describtion of file functions---------------
  // This Macro calculates and returns the effective areas 
  // and the the profile plots  
  //
  // Output of this file : 1)  A canvas saved as Bin_X.png 
  // with the Isolation profiles and the Rho fitted for sanity checks 
  // where X is the specific eta bin 
  // 
  // 2) A file called Bin_X_ProfPlots.root containing the fitted profile 
  // plots of the Rho and three isolations.
  //
  // 3)It returns (as a function) the three effective areas under the names :
  // isoP, isoC, isoN, by changing the variables to these values that are 
  // fed to it.  
  //
  //
  // Required Input to this Macro: 3 variables that must be checked to 
  // correspond to the correct isolation, to be changed and given the 
  // effective areas values. 
  // The Bin number of eta, because with that we open the file 
  // containing the 2d plots to create the profles. And thus these files 
  // must exist. These files are generated by the AreaCalc.C macro.
  //
  //
  //-------------------------------------------------------------------------
  
  



  ostringstream biin; 
  biin << bin; 
  string fop = "./EfAreas/AreaCalc_"+biin.str()+".root";
  string fou = "./EfAreas/Bin_"+biin.str()+"ProfPlots.root";
  string Pngg = "./EfAreas/Bin_"+biin.str()+".png";

  const char *fnmm = fop.c_str();
  const char *outP = fou.c_str();
  const char *PNG = Pngg.c_str();

  TFile *f1 = new TFile(fnmm);
  TFile *f2 = new TFile("CompatV_test.root");

  f2->cd();
  TProfile *RvsPVp = RvsPV->ProfileX();
  
  f1->cd();  
  TProfile *IsoPvsPVsp = IsoPvsPVs->ProfileX();
  TProfile *IsoCvsPVsp = IsoCvsPVs->ProfileX();
  TProfile *IsoNvsPVsp = IsoNvsPVs->ProfileX();
    
  gStyle->SetOptStat(0);
  gStyle->SetOptFit(1111);


  TF1 *fn1 = new TF1("fn1","[0]*x + [1]",10,25);
  TF1 *fn2 = new TF1("fn2","[0]*x + [1]",10,25);
  TF1 *fn3 = new TF1("fn3","[0]*x + [1]",10,25);
  TF1 *fn4 = new TF1("fn4","[0]*x + [1]",10,25);

  //Fitting the Profile plots

  RvsPVp->Fit("fn1","R");
  IsoPvsPVsp->Fit("fn2","R");
  IsoNvsPVsp->Fit("fn3","R");
  IsoCvsPVsp->Fit("fn4","R");


 
  TCanvas *c1  = new TCanvas("c1","Iso and Rhos",1000,1000,700,700);
  c1->Divide(2,2);
  c1->cd(1);
  RvsPVp->Draw();
  RvsPVp->GetXaxis()->SetTitle(" # of Vertices ");
  RvsPVp->GetYaxis()->SetTitle(" Rho Profile ");
 

 
  c1->cd(2);
  IsoPvsPVsp->Draw();                                                           
  IsoPvsPVsp->GetXaxis()->SetTitle(" # of Vertices ");
  IsoPvsPVsp->GetYaxis()->SetTitle(" Iso Profile ");


  c1->cd(3);
  IsoNvsPVsp->Draw();    
  IsoNvsPVsp->GetXaxis()->SetTitle(" # of Vertices ");
  IsoNvsPVsp->GetYaxis()->SetTitle(" Iso Profile ");
  
  c1->cd(4);
  IsoCvsPVsp->Draw();    
  IsoCvsPVsp->GetXaxis()->SetTitle(" # of Vertices ");
  IsoCvsPVsp->GetYaxis()->SetTitle(" Iso Profile ");


  c1->SaveAs(PNG);

  //Retrieving the fit parameters to derive effective areas  

  TF1 *fgm  = IsoPvsPVsp->GetFunction("fn2");
  TF1 *fne  = IsoNvsPVsp->GetFunction("fn3");
  TF1 *fR   = RvsPVp->GetFunction("fn1");
  TF1 *fch1 = IsoCvsPVsp->GetFunction("fn4");

  double Rho_a  = fR->GetParameter(0);
  double Isog_a = fgm->GetParameter(0);
  double Ison_a = fne->GetParameter(0);
  double Isoc_a = fch1->GetParameter(0);
   

 
  
  cout<<"-------------effective areas -----"<<endl;
  
  cout<<" gammas  iso EA :"<< Isog_a/Rho_a<<endl;
  cout<<" neutral iso EA :"<< Ison_a/Rho_a<<endl;
  cout<<" charge  iso EA :"<< Isoc_a/Rho_a<<endl;


  isoP = (Isog_a/Rho_a);
  isoN = (Ison_a/Rho_a);
  isoC = (Isoc_a/Rho_a);

  
  TFile *f3 = new TFile(outP,"RECREATE");
  f3->cd();
  RvsPVp->Write();
  IsoPvsPVsp->Write();                                                                                
  IsoCvsPVsp->Write();                                                                                
  IsoNvsPVsp->Write();                                                                                
                                                                                                      

  f3->Close();
}
